contact_links:
    - name: Ask questions from the GIS community
      url: https://gis.stackexchange.com
      about: To get answers from questions in the GIS commminuty, please ask and answer questions here.
